### ISSUE TITLE
uninitialized constant CheddarGetter (NameError)

### ISSUE THREAD

**Issue by charliezhao** [ads/cheddargetter#4]
After installing Cheddargetter gem by "gem install cheddargetter", I run my rails app, but I got the following error.

Why did I miss?

> ruby script/server -p 3000
> => Booting WEBrick
> => Rails 2.3.5 application starting on http://0.0.0.0:3000
> /home/czhao/.gem/ruby/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:443:in `load_missing_constant': uninitialized constant CheddarGetter (NameError)

**Comment by jonnii** [comment]
I think you need to add :lib => 'cheddar_getter' do your environment.rb

**Comment by jonnii** [comment]
also i suggest upgrading to a newer version of rails.  the latest for 2.x is 2.3.9.

**Comment by charliezhao** [comment]
I have these lines in my environment.rb:
 config.gem "cheddargetter", :lib => 'cheddar_getter', :version => '0.1.1'
  @cheddar_getter = CheddarGetter.new('email', 'password', 'MYPRODUCT')

Still got uninitialized constant CheddarGetter (NameError).

I am using rails 2.3.5. Is 2.3.9 is required to run cheddargetter?

**Comment by jonnii** [comment]
Try this:

config.gem 'cheddargetter', :lib => 'cheddargetter'

This is what I have in my environment.rb

I don't think you need a later version of rails, but even so, you should consider upgrading for plenty of other reasons.

**Comment by charliezhao** [comment]
Thanks a lot for your prompt response. However, I still have the same error. There must be something else going.

**Comment by charliezhao** [comment]
problem was solved by clone the git, build the gem file and install it.
